// src/lib/components/App/Preview.svelte
<script lang="ts">
	import { DEFAULT_FONT_FAMILY, SCHEMA_DEFAULTS } from '$lib/schema/schema';
	import type { TypeScale } from '$lib/types';
	import type { Readable } from 'svelte/store';
	import { useFormState } from '$lib/schema/schema.utils';
	import { getGoogleFontLinkTagHref } from '$lib/utils';
	import Fieldset from '../Fieldset.svelte';
	import type { SelectProps } from '../Select.types';
	import GoogleFontSelect from '../GoogleFontSelect.svelte';
	import RangeInput from '../RangeInput.svelte';
	import Label from '../Label.svelte';
	import { Param } from '$lib/schema/schema';
	import Input from '../Input.svelte';
	import Button from '../Button.svelte';

	export let typeScale: Readable<TypeScale>;

	const { form, errors, constraints } = useFormState();
	$: previewFont = $form[Param.previewFont];
	$: previewText = $form[Param.previewText];
	$: previewWidth = $form[Param.previewWidth];
	$: typeScaleEntries = $typeScale.entries();
	$: isDefaultFontFamily = previewFont === DEFAULT_FONT_FAMILY;

	const handleFontInput: SelectProps['onInput'] = (e) => {
		form.set({
			...$form,
			[Param.previewFont]: (e.target as HTMLOptionElement).value
		});
	};
</script>

<svelte:head>
	{#if !isDefaultFontFamily}
		<link
			rel="stylesheet"
			type="text/css"
			href={getGoogleFontLinkTagHref({
				family: previewFont,
				display: 'swap'
			})}
		/>
	{/if}
</svelte:head>
<section class="preview">
	<h2>Preview your type scale</h2>
	<Fieldset title="Preview controls" isLegendVisuallyHidden={true}>
		<Label title="Font family">
			<GoogleFontSelect
				name={Param.previewFont}
				value={previewFont}
				errors={$errors[Param.previewFont]}
				constraints={$constraints[Param.previewFont]}
				onInput={handleFontInput}
			/>
		</Label>
		<Label title="Preview text">
			<Input
				name={Param.previewText}
				type="text"
				value={previewText}
				errors={$errors[Param.previewText]}
				constraints={$constraints[Param.previewText]}
				onInput={(e) =>
					form.set({
						...$form,
						[Param.previewText]: e.currentTarget.value
					})}
			/>
		</Label>
		<RangeInput
			name={Param.previewWidth}
			label={`${$form[Param.shouldUseContainerWidth] ? 'Container' : 'Screen'} width (px)`}
			value={previewWidth}
			errors={$errors[Param.previewWidth]}
			constraints={{
				...$constraints[Param.previewWidth],
				min: $form[Param.minWidth],
				max: $form[Param.maxWidth]
			}}
			onInput={(e) =>
				form.set({
					...$form,
					[Param.previewWidth]: e.currentTarget.valueAsNumber
				})}
		/>
		<noscript>
			<Button type="submit">Update table</Button>
		</noscript>
	</Fieldset>
	<div class="table-wrapper" tabIndex={0} role="region" aria-label="Size previews">
		<table>
			<thead>
				<tr>
					<th scope="col">Step</th>
					<th scope="col" class="numeric nowrap"> Min </th>
					<th scope="col" class="numeric nowrap"> Max </th>
					<th scope="col" class="numeric nowrap"> Rendered </th>
					<th scope="col" class="preview-text nowrap"> Preview </th>
				</tr>
			</thead>
			<tbody>
				{#each typeScaleEntries as [step, { min, max, getFontSizeAtScreenWidth }]}
					<tr>
						<td>{step}</td>
						<td class="numeric">{min}</td>
						<td class="numeric">{max}</td>
						<td class="numeric">{getFontSizeAtScreenWidth(previewWidth)}</td>
						<td
							class="nowrap"
							style={`font-size: calc(${getFontSizeAtScreenWidth(previewWidth)} * ${
								$form[Param.shouldUseRems] ? $form[Param.remValueInPx] : SCHEMA_DEFAULTS.remValue
							}/${SCHEMA_DEFAULTS.remValue}); font-family: ${isDefaultFontFamily ? 'var(--ff-body)' : previewFont}`}
						>
							{previewText}
						</td>
					</tr>
				{/each}
			</tbody>
		</table>
	</div>
</section>

<style lang="scss">
	@import '../../styles/functions';
	@import '../../styles/mixins';

	.preview {
		max-width: 100%;
		width: 100%;
		overflow: hidden;
		padding: 0 4px;
		display: grid;
		gap: var(--sp-2xl);
	}
	h2 {
		margin: 0;
	}

	.table-wrapper {
		max-width: 100%;
		overflow: auto;
		width: 100%;
	}
	table {
		--cell-padding: var(--sp-xs);
		border-collapse: collapse;
		// https://github.com/AleksandrHovhannisyan/fluid-type-scale-calculator/issues/14
		font-variant-numeric: tabular-nums;
		margin-left: calc(-1 * var(--cell-padding));
		margin-right: calc(-1 * var(--cell-padding));
	}
	:is(th, td) {
		border: none;
		padding: var(--cell-padding);
	}
	th {
		text-align: start;
		font-weight: var(--fw-body-bold);
		padding-top: 0;
	}
	.numeric {
		text-align: end;
	}
	.nowrap {
		white-space: nowrap;
	}
</style>

// src/_includes/components/Preview.jsx
import { useState } from 'react';
import Input from './Input';
import RangeInput from './RangeInput';

// No need to use a Head lib
const getFontLinkTag = (id) => {
  const existingLink = document.getElementById(id);
  if (existingLink) {
    document.head.removeChild(existingLink);
  }
  const link = document.createElement('link');
  link.removeEventListener('load', onLinkLoaded);
  link.id = id;
  link.rel = 'stylesheet';
  return link;
};

const onLinkLoaded = (fontFamily, previewText, setFont) => async () => {
  await document.fonts.load(`1em ${fontFamily}`, previewText);
  setFont(fontFamily);
};

const Preview = ({ baseSizes, typeScale, fonts }) => {
  const [previewText, setPreviewText] = useState('Almost before we knew it, we had left the ground');
  const [previewFont, setPreviewFont] = useState('Inter');
  const [screenWidth, setScreenWidth] = useState(baseSizes.max.screenWidth);

  const onFontSelected = async (fontFamily) => {
    const link = getFontLinkTag('user-selected-font');
    document.head.appendChild(link);
    link.addEventListener('load', onLinkLoaded(fontFamily, previewText, setPreviewFont));
    link.href = `https://fonts.googleapis.com/css2?family=${fontFamily.replace(/ /g, '+')}&display=swap`;
  };

  return (
    <div id="preview" className="flow">
      <h2>Preview your type scale</h2>
      <div className="preview-label-group">
        <RangeInput
          id="screen-width-range"
          label="Screen width (pixels)"
          value={screenWidth}
          onChange={(e) => setScreenWidth(Number(e.target.value))}
          min={0}
          max={baseSizes.max.screenWidth * 1.5}
        />
        <label className="label">
          <span className="label-title">Font family</span>
          <select defaultValue={previewFont} onChange={(e) => onFontSelected(e.target.value)}>
            {fonts.map((fontFamily) => (
              <option key={fontFamily} value={fontFamily}>
                {fontFamily}
              </option>
            ))}
          </select>
        </label>
        <label className="label preview-text-input">
          <span className="label-title">Preview text</span>
          <Input type="text" required defaultValue={previewText} onChange={(e) => setPreviewText(e.target.value)} />
        </label>
      </div>
      <div className="table-wrapper">
        <table>
          <thead>
            <tr>
              <th scope="col">Step</th>
              <th scope="col" className="numeric nowrap">
                Min
              </th>
              <th scope="col" className="numeric nowrap">
                Max
              </th>
              <th scope="col" className="numeric nowrap">
                Rendered
              </th>
              <th scope="col" className="preview-text">
                Preview
              </th>
            </tr>
          </thead>
          <tbody>
            {Object.entries(typeScale).map(([step, { min, max, getFontSizeAtScreenWidth }]) => {
              const fontSize = getFontSizeAtScreenWidth(screenWidth);
              return (
                <tr key={step}>
                  <td>{step}</td>
                  <td className="numeric">{min}</td>
                  <td className="numeric">{max}</td>
                  <td className="numeric">{getFontSizeAtScreenWidth(screenWidth)}</td>
                  <td className="preview-text nowrap" style={{ fontSize, fontFamily: previewFont }}>
                    {previewText}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
};
export default Preview;
