// src/lib/components/App/Form/GroupMaximum.svelte
<script>
	import Fieldset from '$lib/components/Fieldset.svelte';
	import Input from '$lib/components/Input.svelte';
	import Label from '$lib/components/Label.svelte';
	import TypeScalePicker from '$lib/components/TypeScalePicker.svelte';
	import { Param } from '$lib/schema/schema';
	import { useFormState } from '$lib/schema/schema.utils';

	const { form, errors, constraints } = useFormState();
</script>

<Fieldset
	title="Maximum (Desktop)"
	description={`At this maximum ${
		$form.useContainerWidth ? 'container' : 'viewport'
	} width, all font sizes in your type scale are computed as the base font size times a power of your chosen ratio.`}
>
	<Label>
		Base font size (px)
		<Input
			type="number"
			inputmode="decimal"
			name={Param.maxFontSize}
			value={$form[Param.maxFontSize]}
			errors={$errors[Param.maxFontSize]}
			constraints={$constraints[Param.maxFontSize]}
			onInput={(e) =>
				form.set({ ...$form, [Param.maxFontSize]: e.currentTarget.valueAsNumber })}
		/>
	</Label>
	<Label>
		{$form.useContainerWidth ? 'Container' : 'Screen'} width (px)
		<Input
			type="number"
			inputmode="decimal"
			name={Param.maxWidth}
			value={$form[Param.maxWidth]}
			errors={$errors[Param.maxWidth]}
			constraints={$constraints[Param.maxWidth]}
			onInput={(e) =>
				form.set({ ...$form, [Param.maxWidth]: e.currentTarget.valueAsNumber })}
		/>
	</Label>
	<TypeScalePicker
		name={Param.maxRatio}
		value={$form[Param.maxRatio]}
		errors={$errors[Param.maxRatio]}
		constraints={$constraints[Param.maxRatio]}
		onInput={(e) => form.set({ ...$form, [Param.maxRatio]: e.currentTarget.valueAsNumber })}
	/>
</Fieldset>

// src/_includes/components/FluidTypeScaleCalculator/Form/GroupMaximum/index.jsx
import { Action } from '../../../constants';
import Input from '../../../Input';
import Label from '../../../Label';
import LabelGroup from '../../../Label/LabelGroup';
import TypeScalePicker from '../../TypeScalePicker';

/**
 * @param {Pick<import("../../typedefs").AppState, 'max'> & { dispatch: import("../../typedefs").AppDispatcher; minScreenWidth: number }} props
 */
const GroupMaximum = (props) => {
  const { max, dispatch, minScreenWidth } = props;

  return (
    <Label
      as="fieldset"
      title="Maximum (Desktop)"
      description="Define the maximum font size and viewport width for your type scale's baseline step. The max font size for all other steps is this baseline font size scaled up/down by your chosen type scale ratio."
    >
      <LabelGroup>
        <label>
          Base font size (pixels)
          <Input
            type="number"
            required={true}
            min={0}
            defaultValue={max.fontSize}
            onChange={(e) =>
              dispatch({
                type: Action.SET_MAX,
                payload: {
                  fontSize: Number(e.target.value),
                },
              })
            }
          />
        </label>
        <label>
          Screen width (pixels)
          <Input
            type="number"
            required={true}
            min={minScreenWidth + 1}
            defaultValue={max.screenWidth}
            onChange={(e) =>
              dispatch({
                type: Action.SET_MAX,
                payload: {
                  screenWidth: Number(e.target.value),
                },
              })
            }
          />
        </label>
        <TypeScalePicker
          ratio={max.modularRatio}
          onChange={(e) => dispatch({ type: Action.SET_MAX, payload: { modularRatio: Number(e.target.value) } })}
        />
      </LabelGroup>
    </Label>
  );
};

export default GroupMaximum;
