// src/components/FluidTypeScaleCalculator/Preview/Preview.tsx
import { ChangeEvent } from 'react';
import { useCallback } from 'react';
import clsx from 'clsx';
import Head from 'next/head';
import { DEFAULT_FONT_FAMILY, Fonts } from '../../../constants';
import { QueryParamId } from '../../../schema/schema.types';
import type { TypeScale, WithFonts } from '../../../types';
import { getGoogleFontLinkTagHref } from '../../../utils';
import Button from '../../Button/Button';
import Fieldset from '../../Fieldset/Fieldset';
import GoogleFontsPicker from '../../GoogleFontsPicker/GoogleFontsPicker';
import Input from '../../Input/Input';
import Label from '../../Label/Label';
import RangeInput from '../../RangeInput/RangeInput';
import { initialFormState, useFormState } from '../FluidTypeScaleCalculator.context';
import styles from './Preview.module.scss';

type Props = WithFonts & {
  /** The type scale to preview. */
  typeScale: TypeScale;
};

const Preview = (props: Props) => {
  const { fonts, typeScale } = props;
  const { state, dispatch } = useFormState();
  const isDefaultFontFamily = state.preview.fontFamily === DEFAULT_FONT_FAMILY;

  const handlePreviewFontChange = useCallback((e: ChangeEvent<HTMLSelectElement>) => {
    const fontFamily = e.target.value;
    dispatch({ type: 'setPreview', payload: { fontFamily } });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handlePreviewTextChange = useCallback((e: ChangeEvent<HTMLInputElement>) => {
    const previewText = e.target.value;
    dispatch({ type: 'setPreview', payload: { text: previewText } });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handlePreviewWidthChange = useCallback((e: ChangeEvent<HTMLInputElement>) => {
    const previewWidth = e.target.valueAsNumber;
    dispatch({ type: 'setPreview', payload: { width: previewWidth } });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      {/* Don't make a duplicate request for the default font since we're self-hosting that. */}
      {!isDefaultFontFamily && (
        <Head>
          <link
            rel="stylesheet"
            type="text/css"
            href={getGoogleFontLinkTagHref({ family: state.preview.fontFamily, display: 'swap' })}
          />
        </Head>
      )}
      <section className={styles.preview}>
        <h2>Preview your type scale</h2>
        <Fieldset
          title="Preview controls"
          isLegendVisuallyHidden={true}
          labelGroupClassName={styles['label-group']}
        >
          <Label title="Font family">
            <GoogleFontsPicker
              name={QueryParamId.previewFont}
              fonts={fonts}
              defaultValue={state.preview.fontFamily}
              onChange={handlePreviewFontChange}
            />
          </Label>
          <Label title="Preview text" className={clsx('label', styles['preview-text-label'])}>
            <Input
              name={QueryParamId.previewText}
              type="text"
              required={true}
              defaultValue={state.preview.text}
              delay={0}
              onChange={handlePreviewTextChange}
            />
          </Label>
          <RangeInput
            id="screen-width-range"
            name={QueryParamId.previewWidth}
            min={0}
            label="Screen width (pixels)"
            value={state.preview.width}
            onChange={handlePreviewWidthChange}
            required={true}
            numericInputClassName={styles['preview-width-input']}
          />
        </Fieldset>
        <noscript>
          <Button type="submit" className={styles['submit-button']}>
            Update table
          </Button>
        </noscript>
        <div className="table-wrapper" tabIndex={0} role="region" aria-label="Size previews">
          <table>
            <thead>
              <tr>
                <th scope="col">Step</th>
                <th scope="col" className="numeric nowrap">
                  Min
                </th>
                <th scope="col" className="numeric nowrap">
                  Max
                </th>
                <th scope="col" className="numeric nowrap">
                  Rendered
                </th>
                <th scope="col" className={clsx(styles['preview-text'], 'nowrap')}>
                  Preview
                </th>
              </tr>
            </thead>
            <tbody>
              {Array.from(typeScale.entries()).map(
                ([step, { min, max, getFontSizeAtScreenWidth }]) => {
                  const fontSize = getFontSizeAtScreenWidth(state.preview.width);
                  const remValue = state.shouldUseRems
                    ? state.remValueInPx
                    : initialFormState.remValueInPx;
                  return (
                    <tr key={step}>
                      <td>{step}</td>
                      <td className="numeric">{min}</td>
                      <td className="numeric">{max}</td>
                      <td className="numeric">{fontSize}</td>
                      <td
                        className="nowrap"
                        style={{
                          fontSize: `calc(${fontSize} * ${remValue}/${initialFormState.remValueInPx})`,
                          fontFamily: isDefaultFontFamily
                            ? Fonts.BODY.style.fontFamily
                            : state.preview.fontFamily,
                        }}
                      >
                        {state.preview.text}
                      </td>
                    </tr>
                  );
                }
              )}
            </tbody>
          </table>
        </div>
      </section>
    </>
  );
};

export default Preview;

// src/lib/components/App/Preview.svelte
<script lang="ts">
	import { DEFAULT_FONT_FAMILY, SCHEMA_DEFAULTS } from '$lib/schema/schema';
	import type { TypeScale } from '$lib/types';
	import type { Readable } from 'svelte/store';
	import { useFormState } from '$lib/schema/schema.utils';
	import { getGoogleFontLinkTagHref } from '$lib/utils';
	import Fieldset from '../Fieldset.svelte';
	import type { SelectProps } from '../Select.types';
	import GoogleFontSelect from '../GoogleFontSelect.svelte';
	import RangeInput from '../RangeInput.svelte';
	import Label from '../Label.svelte';
	import { Param } from '$lib/schema/schema';
	import Input from '../Input.svelte';
	import Button from '../Button.svelte';

	export let typeScale: Readable<TypeScale>;

	const { form, errors, constraints } = useFormState();
	$: previewFont = $form[Param.previewFont];
	$: previewText = $form[Param.previewText];
	$: previewWidth = $form[Param.previewWidth];
	$: typeScaleEntries = $typeScale.entries();
	$: isDefaultFontFamily = previewFont === DEFAULT_FONT_FAMILY;

	const handleFontInput: SelectProps['onInput'] = (e) => {
		form.set({
			...$form,
			[Param.previewFont]: (e.target as HTMLOptionElement).value
		});
	};
</script>

<svelte:head>
	{#if !isDefaultFontFamily}
		<link
			rel="stylesheet"
			type="text/css"
			href={getGoogleFontLinkTagHref({
				family: previewFont,
				display: 'swap'
			})}
		/>
	{/if}
</svelte:head>
<section class="preview">
	<h2>Preview your type scale</h2>
	<Fieldset title="Preview controls" isLegendVisuallyHidden={true}>
		<Label title="Font family">
			<GoogleFontSelect
				name={Param.previewFont}
				value={previewFont}
				errors={$errors[Param.previewFont]}
				constraints={$constraints[Param.previewFont]}
				onInput={handleFontInput}
			/>
		</Label>
		<Label title="Preview text">
			<Input
				name={Param.previewText}
				type="text"
				value={previewText}
				errors={$errors[Param.previewText]}
				constraints={$constraints[Param.previewText]}
				onInput={(e) =>
					form.set({
						...$form,
						[Param.previewText]: e.currentTarget.value
					})}
			/>
		</Label>
		<RangeInput
			name={Param.previewWidth}
			label={`${$form[Param.shouldUseContainerWidth] ? 'Container' : 'Screen'} width (px)`}
			value={previewWidth}
			errors={$errors[Param.previewWidth]}
			constraints={{
				...$constraints[Param.previewWidth],
				min: $form[Param.minWidth],
				max: $form[Param.maxWidth]
			}}
			onInput={(e) =>
				form.set({
					...$form,
					[Param.previewWidth]: e.currentTarget.valueAsNumber
				})}
		/>
		<noscript>
			<Button type="submit">Update table</Button>
		</noscript>
	</Fieldset>
	<div class="table-wrapper" tabIndex={0} role="region" aria-label="Size previews">
		<table>
			<thead>
				<tr>
					<th scope="col">Step</th>
					<th scope="col" class="numeric nowrap"> Min </th>
					<th scope="col" class="numeric nowrap"> Max </th>
					<th scope="col" class="numeric nowrap"> Rendered </th>
					<th scope="col" class="preview-text nowrap"> Preview </th>
				</tr>
			</thead>
			<tbody>
				{#each typeScaleEntries as [step, { min, max, getFontSizeAtScreenWidth }]}
					<tr>
						<td>{step}</td>
						<td class="numeric">{min}</td>
						<td class="numeric">{max}</td>
						<td class="numeric">{getFontSizeAtScreenWidth(previewWidth)}</td>
						<td
							class="nowrap"
							style={`font-size: calc(${getFontSizeAtScreenWidth(previewWidth)} * ${
								$form[Param.shouldUseRems] ? $form[Param.remValueInPx] : SCHEMA_DEFAULTS.remValue
							}/${SCHEMA_DEFAULTS.remValue}); font-family: ${isDefaultFontFamily ? 'var(--ff-body)' : previewFont}`}
						>
							{previewText}
						</td>
					</tr>
				{/each}
			</tbody>
		</table>
	</div>
</section>

<style lang="scss">
	@import '../../styles/functions';
	@import '../../styles/mixins';

	.preview {
		max-width: 100%;
		width: 100%;
		overflow: hidden;
		padding: 0 4px;
		display: grid;
		gap: var(--sp-2xl);
	}
	h2 {
		margin: 0;
	}

	.table-wrapper {
		max-width: 100%;
		overflow: auto;
		width: 100%;
	}
	table {
		--cell-padding: var(--sp-xs);
		border-collapse: collapse;
		// https://github.com/AleksandrHovhannisyan/fluid-type-scale-calculator/issues/14
		font-variant-numeric: tabular-nums;
		margin-left: calc(-1 * var(--cell-padding));
		margin-right: calc(-1 * var(--cell-padding));
	}
	:is(th, td) {
		border: none;
		padding: var(--cell-padding);
	}
	th {
		text-align: start;
		font-weight: var(--fw-body-bold);
		padding-top: 0;
	}
	.numeric {
		text-align: end;
	}
	.nowrap {
		white-space: nowrap;
	}
</style>
