// src/lib/components/App/Form/GroupMinimum.svelte
<script>
	import Fieldset from '$lib/components/Fieldset.svelte';
	import Input from '$lib/components/Input.svelte';
	import Label from '$lib/components/Label.svelte';
	import TypeScalePicker from '$lib/components/TypeScalePicker.svelte';
	import { Param } from '$lib/schema/schema';
	import { useFormState } from '$lib/schema/schema.utils';

	const { form, errors, constraints } = useFormState();
</script>

<Fieldset
	title="Minimum (Mobile)"
	description={`At this minimum ${
		$form.useContainerWidth ? 'container' : 'viewport'
	} width, all font sizes in your type scale are computed as the base font size times a power of your chosen ratio.`}
>
	<Label>
		Base font size (px)
		<Input
			type="number"
			inputmode="decimal"
			name={Param.minFontSize}
			value={$form[Param.minFontSize]}
			errors={$errors[Param.minFontSize]}
			constraints={$constraints[Param.minFontSize]}
			onInput={(e) => form.set({ ...$form, [Param.minFontSize]: e.currentTarget.valueAsNumber })}
		/>
	</Label>
	<Label>
		{$form.useContainerWidth ? 'Container' : 'Screen'} width (px)
		<Input
			type="number"
			inputmode="decimal"
			name={Param.minWidth}
			value={$form[Param.minWidth]}
			errors={$errors[Param.minWidth]}
			constraints={$constraints[Param.minWidth]}
			onInput={(e) => form.set({ ...$form, [Param.minWidth]: e.currentTarget.valueAsNumber })}
		/>
	</Label>
	<TypeScalePicker
		name={Param.minRatio}
		value={$form[Param.minRatio]}
		errors={$errors[Param.minRatio]}
		constraints={$constraints[Param.minRatio]}
		onInput={(e) => form.set({ ...$form, [Param.minRatio]: e.currentTarget.valueAsNumber })}
	/>
</Fieldset>

// src/_includes/components/FluidTypeScaleCalculator/Form/GroupMinimum/GroupMinimum.jsx
import { Action } from '../../../constants';
import Input from '../../../Input/Input';
import Label from '../../../Label/Label';
import LabelGroup from '../../../Label/LabelGroup/LabelGroup';
import TypeScalePicker from '../../TypeScalePicker/TypeScalePicker';

/**
 * @param {Pick<import("../../typedefs").AppState, 'min'> & { dispatch: import("../../typedefs").AppDispatcher; maxScreenWidth: number }} props
 */
const GroupMinimum = (props) => {
  const { min, dispatch, maxScreenWidth } = props;
  return (
    <Label
      as="fieldset"
      title="Minimum (Mobile)"
      description="Define the minimum font size and viewport width for your type scale's baseline step. The minimum font size for all other steps is this baseline font size scaled up/down by your chosen type scale ratio."
    >
      <LabelGroup>
        <Label>
          Base font size (pixels)
          <Input
            type="number"
            required={true}
            min={0}
            defaultValue={min.fontSize}
            onChange={(e) =>
              dispatch({
                type: Action.SET_MIN,
                payload: {
                  fontSize: Number(e.target.value),
                },
              })
            }
          />
        </Label>
        <Label>
          Screen width (pixels)
          <Input
            type="number"
            required={true}
            min={0}
            max={maxScreenWidth - 1}
            defaultValue={min.screenWidth}
            onChange={(e) =>
              dispatch({
                type: Action.SET_MIN,
                payload: {
                  screenWidth: Number(e.target.value),
                },
              })
            }
          />
        </Label>
        <TypeScalePicker
          id="type-scale-min"
          ratio={min.modularRatio}
          onChange={(e) => dispatch({ type: Action.SET_MIN, payload: { modularRatio: Number(e.target.value) } })}
        />
      </LabelGroup>
    </Label>
  );
};

export default GroupMinimum;
