// src/components/FluidTypeScaleCalculator/Form/GroupMinimum/GroupMinimum.tsx
import { QUERY_PARAM_CONFIG } from '../../../../api/api.constants';
import Fieldset from '../../../Fieldset/Fieldset';
import Input from '../../../Input/Input';
import Label from '../../../Label/Label';
import { useFormState } from '../../FluidTypeScaleCalculator.context';
import TypeScalePicker from '../../TypeScalePicker/TypeScalePicker';

const GroupMinimum = () => {
  const { state, dispatch } = useFormState();
  return (
    <Fieldset
      title="Minimum (Mobile)"
      description="Define the minimum font size and viewport width for your type scale's baseline step. The minimum font size for all other steps is this baseline font size scaled up/down by your chosen type scale ratio."
    >
      <Label>
        Base font size (pixels)
        <Input
          type="number"
          name="minFontSize"
          required={true}
          min={QUERY_PARAM_CONFIG.minFontSize.min}
          max={QUERY_PARAM_CONFIG.minFontSize.max}
          defaultValue={state.min.fontSize}
          onChange={(e) =>
            dispatch({
              type: 'setMin',
              payload: {
                fontSize: e.target.valueAsNumber,
              },
            })
          }
        />
      </Label>
      <Label>
        Screen width (pixels)
        <Input
          name="minWidth"
          type="number"
          required={true}
          min={QUERY_PARAM_CONFIG.minWidth.min}
          max={state.max.screenWidth - 1}
          defaultValue={state.min.screenWidth}
          onChange={(e) =>
            dispatch({
              type: 'setMin',
              payload: {
                screenWidth: e.target.valueAsNumber,
              },
            })
          }
        />
      </Label>
      <TypeScalePicker
        name="minRatio"
        id="type-scale-min"
        ratio={state.min.ratio}
        min={QUERY_PARAM_CONFIG.minRatio.min}
        max={QUERY_PARAM_CONFIG.minRatio.max}
        onChange={(e) => dispatch({ type: 'setMin', payload: { ratio: e.target.valueAsNumber } })}
      />
    </Fieldset>
  );
};

export default GroupMinimum;

// src/lib/components/App/Form/GroupMinimum.svelte
<script>
	import Fieldset from '$lib/components/Fieldset.svelte';
	import Input from '$lib/components/Input.svelte';
	import Label from '$lib/components/Label.svelte';
	import TypeScalePicker from '$lib/components/TypeScalePicker.svelte';
	import { Param } from '$lib/schema/schema';
	import { useFormState } from '$lib/schema/schema.utils';

	const { form, errors, constraints } = useFormState();
</script>

<Fieldset
	title="Minimum (Mobile)"
	description={`At this minimum ${
		$form.useContainerWidth ? 'container' : 'viewport'
	} width, all font sizes in your type scale are computed as the base font size times a power of your chosen ratio.`}
>
	<Label>
		Base font size (px)
		<Input
			type="number"
			inputmode="decimal"
			name={Param.minFontSize}
			value={$form[Param.minFontSize]}
			errors={$errors[Param.minFontSize]}
			constraints={$constraints[Param.minFontSize]}
			onInput={(e) => form.set({ ...$form, [Param.minFontSize]: e.currentTarget.valueAsNumber })}
		/>
	</Label>
	<Label>
		{$form.useContainerWidth ? 'Container' : 'Screen'} width (px)
		<Input
			type="number"
			inputmode="decimal"
			name={Param.minWidth}
			value={$form[Param.minWidth]}
			errors={$errors[Param.minWidth]}
			constraints={$constraints[Param.minWidth]}
			onInput={(e) => form.set({ ...$form, [Param.minWidth]: e.currentTarget.valueAsNumber })}
		/>
	</Label>
	<TypeScalePicker
		name={Param.minRatio}
		value={$form[Param.minRatio]}
		errors={$errors[Param.minRatio]}
		constraints={$constraints[Param.minRatio]}
		onInput={(e) => form.set({ ...$form, [Param.minRatio]: e.currentTarget.valueAsNumber })}
	/>
</Fieldset>
