// src/components/FluidTypeScaleCalculator/Form/GroupUseContainerWidth/GroupUseContainerWidth.tsx
import { memo } from 'react';
import { QueryParamId } from '../../../../schema/schema.types';
import Input from '../../../Input/Input';
import Label from '../../../Label/Label';
import type { ActionSetShouldUseRems, FormState } from '../../FluidTypeScaleCalculator.types';

type Props = Pick<FormState, 'shouldUseContainerWidth'> & {
  /** Function to update the value for this input. */
  onChange: (payload: ActionSetShouldUseRems['payload']) => void;
};

const GroupUseContainerWidth = (props: Props) => {
  const { shouldUseContainerWidth, onChange } = props;

  return (
    <Label
      title="Use container inline size (cqi) instead of viewport width"
      description="Note: Container queries may not be supported by all browsers."
      layout="horizontal"
    >
      <Input
        type="checkbox"
        name={QueryParamId.shouldUseContainerWidth}
        checked={shouldUseContainerWidth}
        onChange={(e) => onChange(e.target.checked)}
      />
    </Label>
  );
};

export default memo(GroupUseContainerWidth);

// src/lib/components/App/Form/GroupUseContainerWidth.svelte
<script>
	import Checkbox from '$lib/components/Checkbox.svelte';
	import Label from '$lib/components/Label.svelte';
	import { Param } from '$lib/schema/schema';
	import { useFormState } from '$lib/schema/schema.utils';

	const { form, errors, constraints } = useFormState();
	let name = Param.shouldUseContainerWidth;
</script>

<Label
	title="Use container inline size (cqi) instead of viewport width"
	description="Note: Container queries may not be supported by all browsers."
	layout="horizontal"
>
	<Checkbox
		name={name}
		checked={$form[name]}
		errors={$errors[name]}
		constraints={$constraints[name]}
		onInput={(e) =>
			form.set({
				...$form,
				[name]: e.currentTarget.checked
			})}
	/>
</Label>
