// src/_includes/components/FluidTypeScaleCalculator/Form/GroupRounding/index.jsx
import { Action } from '../../../constants';
import Input from '../../../Input';
import Label from '../../../Label';
import styles from './styles.module.scss';

/**
 * @param {Pick<import("../../../typedefs").AppState, 'roundingDecimalPlaces'> & { dispatch: import("../../../typedefs").AppDispatcher } } props
 */
const GroupRounding = (props) => {
  const { roundingDecimalPlaces, dispatch } = props;
  return (
    <div className={styles['group-rounding']}>
      <Label
        title="Rounding"
        description="The maximum number of decimal places in the output."
        htmlFor="group-rounding"
      />
      <Input
        id="group-rounding"
        type="number"
        step={1}
        min={0}
        max={5}
        required={true}
        defaultValue={roundingDecimalPlaces}
        onChange={(e) =>
          dispatch({
            type: Action.SET_ROUNDING_DECIMAL_PLACES,
            payload: Number(e.target.value),
          })
        }
      />
    </div>
  );
};
export default GroupRounding;

// src/lib/components/App/Form/GroupRounding.svelte
<script>
	import Input from '$lib/components/Input.svelte';
	import Label from '$lib/components/Label.svelte';
	import { Param } from '$lib/schema/schema';
	import { useFormState } from '$lib/schema/schema.utils';

	const { form, errors, constraints } = useFormState();
</script>

<Label
	title="Rounding"
	description="The maximum number of decimal places in the output."
	layout="to-horizontal"
	htmlFor={Param.roundingDecimalPlaces}
>
	<Input
		id={Param.roundingDecimalPlaces}
		name={Param.roundingDecimalPlaces}
		type="number"
		step={1}
		value={$form.decimals}
		errors={$errors.decimals}
		constraints={$constraints.decimals}
		onInput={(e) => form.set({ ...$form, decimals: e.currentTarget.valueAsNumber })}
	/>
</Label>
