// src/components/FluidTypeScaleCalculator/Form/GroupIncludeFallbacks/GroupIncludeFallbacks.tsx
import { memo } from 'react';
import { QueryParamId } from '../../../../schema/schema.types';
import Input from '../../../Input/Input';
import Label from '../../../Label/Label';
import type {
  ActionSetShouldIncludeFallbacks,
  FormState,
} from '../../FluidTypeScaleCalculator.types';

type Props = Pick<FormState, 'shouldIncludeFallbacks'> & {
  /** Function to update the value for this input. */
  onChange: (payload: ActionSetShouldIncludeFallbacks['payload']) => void;
};

const GroupIncludeFallbacks = (props: Props) => {
  const { shouldIncludeFallbacks, onChange } = props;

  return (
    <Label
      title="Include fallback CSS"
      description="Fall back to media queries if the browser doesn't support clamp."
      layout="horizontal"
    >
      <Input
        type="checkbox"
        name={QueryParamId.shouldIncludeFallbacks}
        checked={shouldIncludeFallbacks}
        onChange={(e) => onChange(e.target.checked)}
      />
    </Label>
  );
};

export default memo(GroupIncludeFallbacks);

// src/lib/components/App/Form/GroupIncludeFallbacks.svelte
<script>
	import Checkbox from '$lib/components/Checkbox.svelte';
	import Label from '$lib/components/Label.svelte';
	import { Param } from '$lib/schema/schema';
	import { useFormState } from '$lib/schema/schema.utils';

	const { form, errors, constraints } = useFormState();
	let name = Param.shouldIncludeFallbacks;
</script>

<Label
	title="Include fallback CSS"
	description="Fall back to media queries if the browser doesn't support clamp."
	layout="horizontal"
>
	<Checkbox
		name={name}
		checked={$form[name]}
		errors={$errors[name]}
		constraints={$constraints[name]}
		onInput={(e) => form.set({ ...$form, [name]: e.currentTarget.checked })}
	/>
</Label>
