// src/lib/components/App/Form/GroupTypeScaleSteps.svelte
<script>
	import Fieldset from '$lib/components/Fieldset.svelte';
	import Input from '$lib/components/Input.svelte';
	import Label from '$lib/components/Label.svelte';
	import Select from '$lib/components/Select.svelte';
	import { Param } from '$lib/schema/schema';
	import { toCommaSeparatedList } from '$lib/utils';
	import { useFormState } from '$lib/schema/schema.utils';

	const { form, errors, constraints } = useFormState();
</script>

<Fieldset
	title="Type scale"
	description="Provide a comma-separated list of names for each step in your type scale, in ascending order of font size. Use any convention you want. Be sure to also identify the name of your base step."
>
	<Label>
		All steps
		<Input
			name={Param.allSteps}
			type="text"
			title="Comma-separated list"
			spellcheck={false}
			value={$form[Param.allSteps]}
			errors={$errors[Param.allSteps]}
			constraints={$constraints[Param.allSteps]}
			onInput={(e) => form.set({ ...$form, [Param.allSteps]: e.currentTarget.value })}
		/>
	</Label>
	<Label>
		Baseline step
		<Select
			name={Param.baseStep}
			options={toCommaSeparatedList($form[Param.allSteps]).map((step) => ({ value: step }))}
			value={$form[Param.baseStep]}
			errors={$errors[Param.baseStep]}
			constraints={$constraints[Param.baseStep]}
			onInput={(e) => form.set({ ...$form, [Param.baseStep]: e.currentTarget.value })}
		/>
	</Label>
</Fieldset>

// src/components/FluidTypeScaleCalculator/Form/GroupTypeScaleSteps/GroupTypeScaleSteps.tsx
import { COMMA_SEPARATED_LIST_REGEX, Delay } from '../../../../constants';
import { toCommaSeparatedList } from '../../../../utils';
import Input from '../../../Input/Input';
import Label from '../../../Label/Label';
import LabelGroup from '../../../Label/LabelGroup/LabelGroup';
import Select from '../../../Select/Select';
import { useFormState } from '../../FluidTypeScaleCalculator.context';

const GroupTypeScaleSteps = () => {
  const { state, dispatch } = useFormState();
  return (
    <Label
      as="fieldset"
      title="Type scale"
      description="Provide a comma-separated list of names for each step in your type scale, in ascending order of font size. Use any convention you want. Be sure to also identify the name of your base step."
    >
      <LabelGroup>
        <Label>
          All steps
          <Input
            name="steps"
            type="text"
            title="Comma-separated list"
            required
            spellCheck="false"
            pattern={COMMA_SEPARATED_LIST_REGEX.source}
            defaultValue={state.typeScaleSteps.all.join(',')}
            delay={Delay.MEDIUM}
            onChange={(e) =>
              dispatch({
                type: 'setTypeScaleSteps',
                payload: { all: toCommaSeparatedList(e.target.value) },
              })
            }
          />
        </Label>
        <Label>
          Baseline step
          <Select
            name="baseStep"
            defaultValue={state.typeScaleSteps.base}
            onChange={(e) =>
              dispatch({
                type: 'setTypeScaleSteps',
                payload: { base: e.target.value },
              })
            }
          >
            {state.typeScaleSteps.all.map((step) => (
              <option key={step} value={step}>
                {step}
              </option>
            ))}
          </Select>
        </Label>
      </LabelGroup>
    </Label>
  );
};

export default GroupTypeScaleSteps;
