// src/lib/components/App/Form/GroupRounding.svelte
<script>
	import Input from '$lib/components/Input.svelte';
	import Label from '$lib/components/Label.svelte';
	import { Param } from '$lib/schema/schema';
	import { useFormState } from '$lib/schema/schema.utils';

	const { form, errors, constraints } = useFormState();
</script>

<Label
	title="Rounding"
	description="The maximum number of decimal places in the output."
	layout="to-horizontal"
>
	<Input
		name={Param.roundingDecimalPlaces}
		type="number"
		step={1}
		value={$form.decimals}
		errors={$errors.decimals}
		constraints={$constraints.decimals}
		onInput={(e) => form.set({ ...$form, decimals: e.currentTarget.valueAsNumber })}
	/>
</Label>

// src/components/FluidTypeScaleCalculator/Form/GroupRounding/GroupRounding.tsx
import { QUERY_PARAM_CONFIG } from '../../../../api/api.constants';
import Input from '../../../Input/Input';
import Label from '../../../Label/Label';
import { useFormState } from '../../FluidTypeScaleCalculator.context';
import styles from './GroupRounding.module.scss';

const GroupRounding = () => {
  const { state, dispatch } = useFormState();
  return (
    <Label title="Rounding" description="The maximum number of decimal places in the output." direction="horizontal">
      <Input
        name="decimals"
        className={styles['rounding-input']}
        type="number"
        step={1}
        min={QUERY_PARAM_CONFIG.decimals.min}
        max={QUERY_PARAM_CONFIG.decimals.max}
        required={true}
        defaultValue={state.roundingDecimalPlaces}
        onChange={(e) =>
          dispatch({
            type: 'setRoundingDecimalPlaces',
            payload: e.target.valueAsNumber,
          })
        }
      />
    </Label>
  );
};
export default GroupRounding;
