// src/lib/components/App/Form/GroupMaximum.svelte
<script>
	import Fieldset from '$lib/components/Fieldset.svelte';
	import Input from '$lib/components/Input.svelte';
	import Label from '$lib/components/Label.svelte';
	import TypeScalePicker from '$lib/components/TypeScalePicker.svelte';
	import { Param } from '$lib/schema/schema';
	import { useFormState } from '$lib/schema/schema.utils';

	const { form, errors, constraints } = useFormState();
</script>

<Fieldset
	title="Maximum (Desktop)"
	description={`At this maximum ${
		$form.useContainerWidth ? 'container' : 'viewport'
	} width, all font sizes in your type scale are computed as the base font size times a power of your chosen ratio.`}
>
	<Label>
		Base font size (px)
		<Input
			type="number"
			inputmode="decimal"
			name={Param.maxFontSize}
			value={$form[Param.maxFontSize]}
			errors={$errors[Param.maxFontSize]}
			constraints={$constraints[Param.maxFontSize]}
			onInput={(e) =>
				form.set({ ...$form, [Param.maxFontSize]: e.currentTarget.valueAsNumber })}
		/>
	</Label>
	<Label>
		{$form.useContainerWidth ? 'Container' : 'Screen'} width (px)
		<Input
			type="number"
			inputmode="decimal"
			name={Param.maxWidth}
			value={$form[Param.maxWidth]}
			errors={$errors[Param.maxWidth]}
			constraints={$constraints[Param.maxWidth]}
			onInput={(e) =>
				form.set({ ...$form, [Param.maxWidth]: e.currentTarget.valueAsNumber })}
		/>
	</Label>
	<TypeScalePicker
		name={Param.maxRatio}
		value={$form[Param.maxRatio]}
		errors={$errors[Param.maxRatio]}
		constraints={$constraints[Param.maxRatio]}
		onInput={(e) => form.set({ ...$form, [Param.maxRatio]: e.currentTarget.valueAsNumber })}
	/>
</Fieldset>

// src/components/FluidTypeScaleCalculator/Form/GroupMaximum/GroupMaximum.tsx
import { memo } from 'react';
import { QueryParamId } from '../../../../schema/schema.types';
import Fieldset from '../../../Fieldset/Fieldset';
import Input from '../../../Input/Input';
import Label from '../../../Label/Label';
import type { ActionSetMax, FormState } from '../../FluidTypeScaleCalculator.types';
import TypeScalePicker from '../../TypeScalePicker/TypeScalePicker';

type Props = Pick<FormState, 'max' | 'shouldUseContainerWidth'> & {
  /** Function to update the value for this input. */
  onChange: (payload: ActionSetMax['payload']) => void;
  /** The minimum allowed value for the screen/container width input. */
  minWidth: FormState['min']['width'];
};

const GroupMaximum = (props: Props) => {
  const { max, minWidth, shouldUseContainerWidth, onChange } = props;

  return (
    <Fieldset
      title="Maximum (Desktop)"
description={`At this maximum ${
        shouldUseContainerWidth ? 'container' : 'viewport'
      } width, all font sizes in your type scale are computed as the base font size times a power of your chosen ratio.`}
    >
      <Label>
        Base font size (px)
        <Input
          name={QueryParamId.maxFontSize}
          type="number"
          required={true}
          min={0}
          defaultValue={max.fontSize}
          onChange={(e) =>
            onChange({
              fontSize: e.target.valueAsNumber,
            })
          }
        />
      </Label>
      <Label>
        {shouldUseContainerWidth ? 'Container' : 'Screen'} width (px)
        <Input
          name={QueryParamId.maxWidth}
          type="number"
          required={true}
          min={minWidth}
          defaultValue={max.width}
          onChange={(e) =>
            onChange({
              width: e.target.valueAsNumber,
            })
          }
        />
      </Label>
      <TypeScalePicker
        name={QueryParamId.maxRatio}
        id="type-scale-max"
        ratio={max.ratio}
        min={0}
        onChange={(e) => onChange({ ratio: e.target.valueAsNumber })}
      />
    </Fieldset>
  );
};

export default memo(GroupMaximum);
