// src/lib/components/App/Form/GroupNamingConvention.svelte
<script>
	import Input from '$lib/components/Input.svelte';
	import Label from '$lib/components/Label.svelte';
	import { Param } from '$lib/schema/schema';
	import { useFormState } from '$lib/schema/schema.utils';

const { form, errors, constraints } = useFormState();
</script>

<Label
	title="Variable prefix"
	description="Use your preferred naming convention for the output CSS variables. Allowed characters: a-z,A-Z,0-9,_,-"
	layout="to-horizontal"
>
	<Input
		name={Param.namingConvention}
		type="text"
		value={$form.prefix}
		errors={$errors.prefix}
		constraints={$constraints.prefix}
		onInput={(e) => form.set({ ...$form, prefix: e.currentTarget.value })}
	/>
</Label>

// src/components/FluidTypeScaleCalculator/Form/GroupNamingConvention/GroupNamingConvention.tsx
import Input from '../../../Input/Input';
import Label from '../../../Label/Label';
import { useFormState } from '../../FluidTypeScaleCalculator.context';

const GroupNamingConvention = () => {
  const { state, dispatch } = useFormState();
  return (
    <Label title="Variable prefix" description="Use whatever naming convention you prefer." layout="to-horizontal">
      <Input
        name="prefix"
        type="text"
        size={10}
        required={true}
        defaultValue={state.namingConvention}
        delay={0}
        onChange={(e) =>
          dispatch({
            type: 'setNamingConvention',
            payload: e.target.value,
          })
        }
      />
    </Label>
  );
};

export default GroupNamingConvention;
