// src/components/FluidTypeScaleCalculator/TypeScalePicker/TypeScalePicker.tsx
import typeScaleRatios from '../../../data/typeScaleRatios.json';
import Input from '../../Input/Input';
import { InputProps } from '../../Input/Input';
import Label from '../../Label/Label';

type TypeScalePickerProps = Omit<InputProps, 'type'> & {
  /** The currently selected numeric type scale ratio. */
  ratio: number;
};

/**
 * Dropdown menu for modular type scales
 */
const TypeScalePicker = (props: TypeScalePickerProps) => {
  const { onChange, ratio, name, id } = props;
  return (
    <Label>
      Type scale ratio
      <Input
        name={name}
        type="number"
        step="any"
        list={id}
        min={0}
        defaultValue={ratio}
        onChange={onChange}
        required={true}
        delay={0}
      />
      <datalist id={id}>
        {Object.entries(typeScaleRatios).map(([key, { name, ratio }]) => {
          return (
            <option key={key} value={ratio}>
              {name}
            </option>
          );
        })}
      </datalist>
    </Label>
  );
};

export default TypeScalePicker;

// src/lib/components/TypeScalePicker.svelte
<script lang="ts" context="module">
	import typeScaleRatios from '../data/typeScaleRatios.json';
</script>

<script lang="ts">
	import type { HTMLInputAttributes } from 'svelte/elements';
	import { createId } from '$lib/utils';
	import Input from './Input.svelte';
	import Label from './Label.svelte';
	import type { Param } from '$lib/schema/schema';
	import type { SchemaConstraints, SchemaErrors } from '$lib/schema/schema';

	export let name: Param.minRatio | Param.maxRatio;
	export let value: HTMLInputAttributes['value'] = undefined;
	export let onInput: HTMLInputAttributes['on:input'] = undefined;
	/** Error messages describing why this input's value is invalid */
	export let errors: SchemaErrors | undefined = undefined;
	/** HTML validation constraints to set on the input */
	export let constraints: SchemaConstraints | undefined = undefined;

	const id = createId('datalist');
</script>

<Label>
	Type scale ratio
	<Input
		{name}
		type="number"
		inputmode="decimal"
		step="any"
		list={id}
		{value}
		{onInput}
		{errors}
		{constraints}
	/>
	<datalist {id}>
		{#each Object.entries(typeScaleRatios) as [_key, { name, ratio }]}
			<option value={ratio}>
				{name}
			</option>
		{/each}
	</datalist>
</Label>
